### ISSUE TITLE
Far funzionare l'app con la nuova api spaggiari

### ISSUE THREAD

**Issue by simoneluconi** [simoneluconi/RegistroElettronico-Android#1]
Far funzionare l'app con la api che spaggiari ha creato per la loro nuova app disponibile al link [https://web.spaggiari.eu/rest/v1/](https://web.spaggiari.eu/rest/v1/)
Apprezziamo lo sforzo ma la vostra app ancora non è all'altezza per quanto ci riguarda

**Comment by luca020400** [comment]
La API ha tutto quello che server, è solo un po' scomoda ...

**Comment by simoneluconi** [comment]
Dicevo la loro app che usa la loro api non è all'altezza 😁

**Comment by luca020400** [comment]
Perfetto si inizia bene.
