### ISSUE TITLE
Google Drive backup

### ISSUE THREAD

**Issue by Quix0tic** [simoneluconi/RegistroElettronico-Android#11]

**Comment by luca020400** [comment]
Well I found this pretty useless, the built-in backup feature handles the database and the preferences

**Comment by simoneluconi** [comment]
I found pretty useless speaking english

**Comment by luca020400** [comment]
Habits

**Comment by Quix0tic** [comment]
Are you sure that the backup will work if the client change device? Keeping the same google account I mean

**Comment by luca020400** [comment]
Yea, this is what Google backup does as long as the account is the same

**Comment by Quix0tic** [comment]
Well, I assume this is useless then
