### ISSUE TITLE
Widgets are not being updated

### ISSUE THREAD

**Issue by Gioxxy** [simoneluconi/RegistroElettronico-Android#25]
Widgets are not updated every day.

**Comment by Gioxxy** [comment]
Using Nova Launcher each time the Launcher is restarted, the data is updated

**Comment by simoneluconi** [comment]
Continuo a non capire perchè parliamo in inglese

**Comment by Quix0tic** [comment]
Can't understand where the problem is.. @Gioxxy

**Comment by Gioxxy** [comment]
@Quix0tic For example if I insert the school timetable/subjects widget in my home, every day does not show me the timetable of the day but remains on the timetable of when I put the widget. This happens using Nova Launcher, I do not know if it works using other Launchers.

**Comment by Quix0tic** [comment]
This is fixed but not released yet due to compiler errors...
