### ISSUE TITLE
Fabric.io è deprecato... Possiamo usare firebase o costa?

### ISSUE THREAD

**Issue by tiziodcaio** [simoneluconi/RegistroElettronico-Android#29]
Scusate l'italiano e l'ignoranza sul campo... Sto tentando di collaborare perché è un bel progetto

**Comment by luca020400** [comment]
Ciao, certo che si può, ma ormai nessuno degli sviluppatori ha più accesso a account classeviva ( siamo tutti universitari ).
Quindi il progetto è morto affinché qualcuno non ne prenda le redini.

**Comment by tiziodcaio** [comment]
Ok... Tento di far girare... Sono di II superiore...

**Comment by luca020400** [comment]
Sentiti libero di chiedere una mano.
Even in English if you prefer.

**Comment by tiziodcaio** [comment]
ok 😎
